name: Publish Server

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - { target: win-x64, os: windows-latest, outname: amnet-server-x64.exe }
          - { target: win-arm64, os: windows-latest, outname: amnet-server-arm64.exe }
          - { target: osx-arm64, os: macos-latest, outname: amnet-server-osx-arm64 }
          - { target: osx-x64, os: macos-latest, outname: amnet-server-osx-x64 }
          - { target: linux-x64, os: ubuntu-latest, outname: amnet-server-linux-x64 }
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish
        run: dotnet publish -r ${{ matrix.target }} -c Release -p:Version=${{ github.event.release.tag_name }} -o publish-out AMNet.Test
 
      - name: Dummy Sign (macOS)
        if: matrix.os == 'macos-latest'
        run: codesign -s - publish-out/amnet-server
        
      - name: Rename (Unix)
        if: matrix.os != 'windows-latest'
        run: mv publish-out/amnet-server publish-out/${{ matrix.outname }}
        
      - name: Rename (Windows)
        if: matrix.os == 'windows-latest'
        run: mv publish-out/amnet-server.exe publish-out/${{ matrix.outname }}
 
      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: publish-out/${{ matrix.outname }}
